apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-backup-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4= #admin
  AWS_SECRET_ACCESS_KEY: V2VzY0BsZVRyYWluMW5n #Wesc@leTrain1ng
  S3_ENDPOINT: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA= #http://minio.minio.svc.cluster.local:9000
  S3_PROVIDER: TWluaW8K #Minio
