apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: application
spec:
  hard:
    requests.cpu: 800m
    requests.memory: 2Gi
    limits.cpu: 1000m
    limits.memory: 3Gi
