{
 "title": "MongoDB Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(mongodb_connections_available, cl_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(mongodb_uptime)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_connections_available", "legendFormat": "Available" },
    { "expr": "mongodb_connections_active", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Mongo Pods Memory Usage in GB / Total Available on Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$Cluster.*\", container=~\"mongodb.*\"})\n",
     "legendFormat": "Working"
    },
    {
     "expr": ":node_memory_MemAvailable_bytes:sum",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Mongo Pods CPU Usage / Total Available on Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$Cluster.*\", image!~\"sha.*\", container=~\"mongo.*\"}[5m]))",
     "legendFormat": "Usage"
    },
    { "expr": "cluster:node_cpu:sum_rate5m", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Catalog Stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_catalogStats_collections{pod=~\"$Cluster.*\"})",
     "legendFormat": "Collections"
    },
    {
     "expr": "max(mongodb_catalogStats_capped{pod=~\"$Cluster.*\"})",
     "legendFormat": "Capped Collections"
    },
    {
     "expr": "max(mongodb_catalogStats_timeseries{pod=~\"$Cluster.*\"})",
     "legendFormat": "Timeseries"
    },
    {
     "expr": "max(mongodb_catalogStats_views{pod=~\"$Cluster.*\"})",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Global Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mongodb_globalLock_activeClients_total{pod=~\"$Cluster.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_readers{pod=~\"$Cluster.*\"})",
     "legendFormat": "Readers"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_writers{pod=~\"$Cluster.*\"})",
     "legendFormat": "Writers"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_metrics_cursor_open_total{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Open"
    },
    {
     "expr": "mongodb_metrics_cursor_open_noTimeout{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Open No Timeout"
    },
    {
     "expr": "mongodb_metrics_cursor_timed_out{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Timed Out"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_metrics_document_inserted{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Inserted"
    },
    {
     "expr": "mongodb_metrics_document_returned{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Returned"
    },
    {
     "expr": "mongodb_metrics_document_deleted{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Deleted"
    },
    {
     "expr": "mongodb_metrics_document_updated{pod=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Updated"
    }
   ]
  },
  {
   "title": "Replication Network Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_repl_network_bytes{pod=~\"$Cluster.*\"})",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_repl_network_ops{pod=~\"$Cluster.*\"})"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(mongodb_network_bytesIn{pod=~\"$Cluster.*\"})",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "max(mongodb_network_bytesOut{pod=~\"$Cluster.*\"})",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(mongodb_opLatencies_reads_latency{pod=~\"$Cluster.*\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "max(mongodb_opLatencies_commands_latency{pod=~\"$Cluster.*\"})",
     "legendFormat": "Commands"
    },
    {
     "expr": "max(mongodb_opLatencies_transactions_latency{pod=~\"$Cluster.*\"})",
     "legendFormat": "Transactions"
    },
    {
     "expr": "max(mongodb_opLatencies_writes_latency{pod=~\"$Cluster.*\"})",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(mongodb_opLatencies_reads_ops{pod=~\"$Cluster.*\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "max(mongodb_opLatencies_commands_ops{pod=~\"$Cluster.*\"})",
     "legendFormat": "Commands"
    },
    {
     "expr": "max(mongodb_opLatencies_transactions_ops{pod=~\"$Cluster.*\"})",
     "legendFormat": "Transactions"
    },
    {
     "expr": "max(mongodb_opLatencies_writes_ops{pod=~\"$Cluster.*\"})",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}