apiVersion: v1
kind: ConfigMap
metadata:
  name: front-admin
  namespace: application
  labels:
    app: microservices-demo
    component: front-admin
data:
  endpoints.json: |-
    {
      "apiArticlesEndpoint": "article"
    }
