apiVersion: v1
kind: ConfigMap
metadata:
  name: article-service
  namespace: application
  labels:
    app: microservices-demo
    component: article-service
data:
  config.yaml: |
    listen: ":8080"
