apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-backup-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4= #admin
  AWS_SECRET_ACCESS_KEY: V2VzY0BsZVRyYWluMW5n #Wesc@leTrain1ng
  S3_ENDPOINT: aHR0cDovL21pbmlvLnZlbGVyby5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw #http://minio.velero.svc.cluster.local:9000
  S3_PROVIDER: TWluaW8K #Minio
