apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql-exporter
      app.kubernetes.io/name: prometheus-mysql-exporter
  endpoints:
  - port: mysql-exporter
