apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: training-sa-list-pods
 namespace: application
roleRef:
 kind: Role
 name: list-pods
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: training-sa
   namespace: application
