apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mysql-exporter-up
  namespace: wordpress
spec:
  groups:
    - name: wordpress.mysql
      rules:
        - alert: NoRunningMysql
          annotations:
            description: Targets are down.
            summary: Targets are down
          expr: up{job="mysql-exporter-prometheus-mysql-exporter"} < 1
          for: 1m
          labels:
            severity: warning
