apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: application
  labels:
    app: microservices-demo
    component: redis
spec:
  selector:
    app: microservices-demo
    component: redis
  ports:
    - port: 6379
